### ISSUE TITLE
Jailer of Love code is off again.

### ISSUE THREAD

**Issue by Miscbox** [myera/issues#12]
Jailer of love loses the ability to regen extremely early on in its add pop cycle. Usually it's about 12 sets of adds before it has the effect greatly diminished but at the moment it stops at about 1-2 pops. It no longer casts spells and obviously in conjunction does not swap elements after a set amount of time. The last issue is that it still approaches the target with enmity to melee attack rather than sit at the full range of the jellyfish cap and cast spells. 

The Spawn Part of the fight : The first set of adds spawns immediately with JoL which should be delayed a bit. The adds themselves are also relatively weak as there seems to be an evasion/accuracy issue on the server again.

Jailer of love is easily sleep-able, bind-able and CC-able and its resistances should be fixed accordingly.

**Comment by Scavenge** [comment]
the guy needs work taht much is clear.  sounds like his queries didn't get included which is easily overlooked during an update because people don't go testing JOL immediately. i've been putting it off for a while, but i need to comb through jailers again and fix a lot of little quirks.  as for the script, i dont know why my script would fire adds early, so it may be a dsp script that's in there right now.

**Comment by Miscbox** [comment]
Are we clear to schedule this as an event soon or has nothing about this changed :x?

**Comment by GM-Dave** [comment]
Warp performed an update to Sea NMs and Jailers some time ago. If there are any current issues they should be addressed in a new ticket.
