### ISSUE TITLE
Things Kevin should check on blu

### ISSUE THREAD

**Issue by hajuhl** [myera/issues#139]
Attempting to start a thread that outlines observations people have made while playing blue. I wanted to outline a couple that I've noticed (I'm also not 100% sure and might need more testing). Here are a couple:
- Most important one imho is that blue magic is not skill chaining correctly (I'm 100% confident on this one). Most of the skills have been allocated to a different part of the skill chart (sickle slash not doing gravitation, cannon ball not forming light from savage blade, Uppercut is doing detonation, Death Scissors is doing Liquefaction, etc).
  
  ```
   - Sub point for this portion: Some magic is not consuming Chain Affinity: the one ones I've actually paid attention to for this has been Sickle Slash and Asuran Claws  (this is probably a separate issue)
  ```
- I have killed around 37 Lamiae tried to learn hysteric barrage. Lamiae seem to be broken right now and will not disarm in any event. I have crit and used dance steps multiple times, and not once have they disarmed. Furthermore, they ONLY use hysteric barrage. I'm not sure if this interferes with Blue Mage learning the spell. 
- Qutrubs in Arrapogo Reef might have a similar disarming issue as the Lamiae. I've only killed around 10, but was unable to disarm any of them. Furthermore, they are blinking nonstop (the same as when players swap equipment without style lock) - this might be the issue? I haven't been able to learn Spinal Cleave from them.
- This is probably a well known issues but since Rafflesias are not using TP skills, we're unable to learn Seedspray.
- I believe Bluemagic learning rate is not correct, as it doesn't seem to be currently affect by your blue magic skill level (I might be wrong about this one)
- Casting Chaotic Eye gives you the message "Character is paralyzed." It doesn't seem like Chaotic Eye is working.

-Certain spells will not consume Chain Affinity, so we're unable to chain them (Asuran Claws and Sickle Slash come to mind)

-Trick attack is not working with Asura Claws and Cannon Ball (enmity is not being transferred). I have not tried with other blue spells, but I'd imagine it would be the same.

Some that are completely conjecture (need more testing):

-Sheep song accuracy seems very low even with capped blue magic
-Pinecone bomb might not be sleeping?
-Sprout Smack slow duration might be off (seems too short for me, but maybe that's how short it should be)

**Comment by Rihce** [comment]
looks good so far bud. we will start progressing now.

**Comment by LocoFFEra** [comment]
This is Courtesy of HYDE & Paiine
----------------------------------------------------

List of Broken BLU Spells - Part 1

*** PLEASE CONSULT THE YOUTUBE VIDEO ***

https://youtu.be/9eELpiIadyg

That should explain things better and or demonstrate what we did and how we found they were broken.

-----------------------------------------------
Part 1 (IN THE ORDER THAT IT APPEARS IN THE VIDEO)

Goblin Rush – Level 81 spell. Should we be able to learn, use, or see this spell if it is above the level cap?

Sandspin - Range of the casting, 5, is low compared to the AoE effect is 8. You can get others larger, this was just the first one on the list. AoE works, Effects work, cast distance seems right.

Queasyshroom - Missing poisoning effect. Range and all works.

Battle Dance - Not shown in video, but accuracy seems wonky. It may have to do with the fact that the monster has the debuff, but I was missing a lot and Paiine wasn't. Maybe take a peek at the code? The range of AoE seems weird being 5 to cast and 4 from centered AoE.

Feather Storm - Range on wiki says 14.7, were getting about 12. This may apply to most ‘ranged’ spells. The poison debuff is missing from the spell. We tried on several non-water mobs.

Poison Breath - Poison effect of spell very wrong. It places it but then it immediately ticks off. Please confirm that ticks are working with the spell, or is it even applying it at all.

Claw Cyclone - Does not stack with SA.

Chaotic Eye - Does not silence. Gives me the error of "HYDE is paralyzed" as if I was. I do not get the Paralyzed icon, seems to be text error. Either way – doesn’t silence the monster - not silencing is bad.

Digest - This one is confusing to explain, it might be better if you play with it. There may not be an issue with the spell damage, but there might be an issue with the text/combat log only displaying what you stole when your HP is down, yet if you are at full health it still displays a constant number (for us is 163). You might have to investigate this one thoroughly. Not sure.

Pinecone Bomb - Sleep effect wears immediately (~.5 sec duration?) similar to Poison Breath. Also, it displays 0 damage, but its doing damage. Cannot tell if the damage is right because it is displaying Zero.

MP Drainkiss - Same as Digest, confirm visuals. Seems to be working otherwise. But does it actually MP DRAIN the monster for the said amount? Can you see on your end if it actually takes away the MP value?

Mysterious Light - Even though vid shows no gravity, I have tried on several mobs and it never proc'd. At all. Also size of AoE seems wrong, similar to Sandspin in terms of initial range to cast it and the size once it casts is not the same.

Magnetite Cloud - Weight debuff doesn’t seem to be correct. I do not know if there is supposed to be the same as a RDM weight, but I am not seeing ANYTHING on wiki about it being different. Otherwise spell works correctly.

Aweful Eye - Applied KO effect instead of STR down affect. I know this used to be a very powerful spell for -STR, up to -33 with a decay over time for the str down. Otherwise Fan-shaped AoE and all other things work.

Blood Saber - Drain is NOT taking away HP from the monsters and GIVING it to caster. It is taking damage, but not given health back. Cannot confirm numbers. Our examples are showing 0 unfortunately.

Jettatura - Always missing when casted. Tried on multiple enemies, same result. Cannot verify TERROR effect.

Spiral Spin - Shouldn't do Zero damage at near zero TP anymore. Video shows difference between low and 1000+ TP. This was tested several times.

Self-Destruct - AoE affect is not being applied to other 
monsters within AoE. Vid shows when tagged, but I also tried monsters that are not tagged and next to the main target either. For the pain of this spell, it should DESTROY EVERYTHING!!! It only killed 1 though. /Sadface

Cold Wave - It aggros, the range is correct, but it is NOT giving the monsters the DOT debuff, which would include an -AGI down AND dot effect to HP. According to the WIKI, it’s supposed to give 'FROST' debuff, while the 0's appearing over the monsters is correct. No indication it’s doing it on our side.

Filamented Hold - Wierd one. In the vid, paiine slows both correctly when he’s at 1000+ TP. Burns his TP, then casts it again on a target already inflicted with the debuff (leech), and it doesn't override. Basically it comes down to TP is affecting potency. It's NOT supposed to do it for this spell. On other tests (not shown in vid) when paiine didn’t gain any TP and constantly recasted it, it override itself w/o an issue. Please look into it.

Light of Penance - Bind effect works great, BLIND is wearing immediately similar to poison breath, and we CANNOT confirm TP loss for enemy. Care to fix the blind and check TP loss (either % or flat value removed?)

Hecatomb Wave - BLIND is wearing immediately. Everything else seems to be working.

Bad Breath - OK... this one is a mass of tangled yarn. Some debuffs are wearing immediately, while some are sticking, some are affected by TP while others are not. You have your work cut out on this one. Good luck, but if you do get it working... there is going to be some monsters that are going to be really sore. :)

Body Slam - Same as a lot of the other Close ranged 
Ranged AoE distance bug like Sandspin.

1000 Needles - It says its doing the damage, it splits the damage, but it doesn’t actually DO the damage. That clipper should have taken SOME damage.

Here is Part 2 (IN THE ORDER THAT IT APPEARS IN THE VIDEO):

https://youtu.be/Bzxpz5m8p2I

Hydro Shot – Not doing Enmity down or Enmity dump. In fact, I drew aggro with it.

Voracious Trunk – Stealing the buff (or ‘dispel’ing) is not happening. Care to check under the hood at the code? Eventually this spell is supposed to steal you monster’s buff, even the crazy ones, but it doesn’t seem to be working properly. Are we having similar issues with this spell and the THF’s merit ability “Aura Steal”?

Regurgitation – missing the (hidden) Additional Effect: Knockback. Otherwise working as intended.

Radiant Breath – the duration of Slow and Silence goes off immediately. I know for sure the spell’s debuffs lasts used to last for 2 minutes, comparable to Frost Breath (both the older version and todays’ version). Please fix this one, this is my favorite spell. Damage seems correct.

Cannonball – SA works (yea!) but the damage overall seems lower than it was before. Care to take a look again at the code?

Lowing – always misses. In addition, the range of the AoE is larger than the distance needed to cast it (reoccurring issue).

Mind Blast – Paralyze effect is correct, but the damage is VERY weak. Shouldn’t be this low. Was doing ~1k to Krakan before.

Ram Charge – Damage might be a little low, but more importantly it’s missing the (hidden) Additional Effect: Knockback similar to Regurgitation.

Spinal Cleave – Untested 

Sub-Zero Smash – Untested 

Triumphant Roar – Untested

Seedspray – Unattainable

**Comment by Rihce** [comment]
very nice. this will give me something to do in my down times

**Comment by Rihce** [comment]
Queasyshroom - Fixed gave code to Warp
Feather Storm - Fixed gave code to Warp
Poison Breath - Fixed gave code to Warp
Disseverment - Fixed gave code to Warp

**Comment by Rihce** [comment]
Radiant Breath - Fixed gave code to Warp

**Comment by Rihce** [comment]
Pinecone Bomb - Fixed gave code to Warp

**Comment by Rihce** [comment]
Bad Breath - Fixed gave code to Warp

**Comment by hajuhl** [comment]
I will have to agree with Hyde and Paiine on cannon ball now that I've tested it. It seems it's not scaling properly. Switching from TP gear to STR/VIT/Def gear is barely affecting its damage.

**Comment by Aerixaa** [comment]
Head Butt range is just broke i need to be insite some Bigger Mobs or i cant cast it i think it should be 10 yalms correct me if I'm wrong.

**Comment by hajuhl** [comment]
Vertical Cleave is not working with Sneak Attack

**Comment by Cloake** [comment]
Cannonball cannot be cast atm.

**Comment by hajuhl** [comment]
Relic Hat is not affecting Breath Damage (it should give +10% dmg) ; This is probably the same for Saurian Helm.

**Comment by Rihce** [comment]
the head butt issue.. the reason you need to be inside bigger mobs isn't because head butt is broke, its because the mobs hit box is broke.

**Comment by hajuhl** [comment]
Cannonball is working with Sneak Attack and IS making Light again! which is great. Defense doesn't seem to be having effect on it right now...

**Comment by hajuhl** [comment]
A couple of questions about cannonball:

- I'm seeing a huge variance; tried in on low level mobs in South Gustaberg and it would range from 1100-1600 with Sneak Attack.
-Defense doesn't seem to be affecting it. At first I thought it was, but the variance can make it seem like it is, while it isn't (I can still hit 1100 while buffed with cocoon, and never got lower than 1100 while unbuffed)
-It's hitting South Gustaberg monsters for 0 damage with Sneak attack at random times

ON THE BRIGHT SIDE:
-It is now creating Light <---- super awesome
-It wasn't working with Sneak Attack after update, but should now be fixed <--- awesome again
