### ISSUE TITLE
Debuff Eva down give 0 eva

### ISSUE THREAD

**Issue by Aerixaa** [myera/issues#17]
Debuff Eva down give 0 eva

http://i.imgur.com/WvDvuRO.jpg

**Comment by Scavenge** [comment]
we actually did a patch to fix this on the same day that you posted this issue.  is it still currently happening?  my own test against infrasonics on lizards worked correctly, and you were right about it from the beginning i must admit.

**Comment by Scavenge** [comment]
https://github.com/DarkstarProject/darkstar/issues/2767

**Comment by Aerixaa** [comment]
Looks like it all Eva down not just from lizzy mobs. When i did Limbus and friend with GA relic got charmend he hit and i got eva down same 0 eva. dont have SS for that because >:> i need to run and i was main healer etc. Going to try other mobs how have eva down like bats etc.

**Comment by Scavenge** [comment]
yeah i agree that it was messed up but i put in a fix for it a few days ago, so it should be fixed now. if you find it happening again at this point, let me know.

the link i added before:

https://github.com/DarkstarProject/darkstar/issues/2767

fixed this issue according to my own tests.  the fix was added to era on 2-20-2016 so what you experienced a few weeks back should be gone now.
