### ISSUE TITLE
Sent items stuck

### ISSUE THREAD

**Issue by wedge2** [myera/issues#187]
![img_20160721_233359](https://cloud.githubusercontent.com/assets/20587175/17041269/d8b142a0-4f9c-11e6-94db-16c48dcec4bb.png)

Could you assist with this?  

I sent roughly 1.5 mil in Gil and a Snipers +1 and its saying sent items are backlogged and i cant retrieve them.  If you try to contact in game, my name is Jaminn or Fullmetal.

**Comment by wedge2** [comment]
Also i sent them to the wrong person.  I think this may be why its having the problem in the first place.

**Comment by LocoFFEra** [comment]
It looks like these items were sent to a character named Wedge. If that's one of yours, you should be able to log onto it and get the items from the delivery box right away.

**Comment by GM-Dave** [comment]
This is a Core/DSP known issue, due to how the delivery system is currently coded. Most we can do is suggest you be careful when sending items to other players or between your characters.

Also, this issue seems to have been resolved. If by chance you are still having issue, pelase file a ticket via the Era HelpDesk (Service Requests link) on the main page.
