### ISSUE TITLE
"Super Tanking" is not working as it does on retail

### ISSUE THREAD

**Issue by Hokuten85** [myera/issues#23]
The concept of Super Tanking on retail has to do with how linked mobs react to a party/alliance in relation to hate accumulation.  When someone aggro's and links mobs, they retain hate indefinitely until an action is performed on one of the linked mobs.  When that mob has an action done on it, then hate within a party can begin accumulating for that mob.  Other linked mobs remain indefinitely targeted on the initial person that aggro'ed until they also have an action done on them.

This applies unless the group of mobs specifically has linked party/alliance hate.  For example, Absolute Virtue has alliance hate. https://www.bg-wiki.com/bg/Absolute_Virtue

It appears that "Super tanking" is not functioning as it does on retail.

It seems that a number of fights in the game were designed with the concept of super tanking in mind.  Multiple unsleepable mobs, that haven't had actions done on them should stay on the initial person aggro'd so they don't immediately switch over to the healer/support party members.

**Comment by Scavenge** [comment]
so if a mob aggros a player you are saying that curing that player should not take the mob's hate?

**Comment by Hokuten** [comment]
If the player performs an action on the mob to gain hate/aggro, then Curing or other actions done by the party should begin accumulating hate on that mob.  If the player aggro's via sight, sound, or link and NO actions have been performed on the mob, then no...curing or other actions performed on that player should not accumulate hate on that mob.  This is basically how PLD holds massive numbers of mobs with Ochain on retail and the mobs never leave him until an action is performed on the mobs. Thus the term Super Tanking because PLD can indefinitely hold mobs while no actions are performed on them.

This applies to most mobs, unless otherwise specifically called out as having shared alliance hate, which means that everyone that is alive and in the party/alliance instantly is on the hate list.

**Comment by Hokuten** [comment]
This bg wiki page discusses it.  It mentions "exploiting game mechanics" and I question the use of the term "exploiting"...but it does utilize a game mechanic that I think is there for a reason, but perhaps wasn't intended to be used to the extent that players are with Ochain in retail.

https://www.bg-wiki.com/bg/Super-(Strategy)

**Comment by dwn134** [comment]
That is correct. I never thought of submitting a ticket for this becuase i thought would be a dsp problem. 
Biggest use i saw this for was divine might. A pld/blu would run in agro everything then blm,s could docus on 1 mob at a time while others could cure pld hate free. 
Its a great tool where you cant sleep mobs  and there is a ton of crowd control

**Comment by GM-Dave** [comment]
Super Tanking & Kiting should work just fine. The issue here is that having enhanced movement speed, players can easily outrun mobs and cause them to de-aggro. You need to make sure you stay within range.

Don't forget that causing the mobs ANY sort of damage or taking any actions that will normal aggro will upset this regardless

**Comment by Hokuten85** [comment]
It's quite possible that it's been fixed.  I haven't played on that server for a number of months, but it most definitely did not work when I put in the ticket all the way up to when I stopped playing.  Maybe October 2016.  You can close this if you'd like as I'm not actively playing on Era atm and I have no real way to test/confirm.

**Comment by GMYasiinEra** [comment]
this has been fixed mob will no longer "lose interest" close this please
