### ISSUE TITLE
SMN AF quest - stuck in a loop "The puppet master"

### ISSUE THREAD

**Issue by Minnaa** [myera/issues#246]
I had completed all AF pieces for SMN about a year ago, but had tossed some of them. To reobtain them, I tossed the remaining pieces as well and started over.

The weapon quest "The Puppet Master" works fine. Completed the quest. Zoned. All good. But then, instead of starting the next quest, "Class Reunion", the house of the hero starts "The Puppet Master all over".

I have completed the puppet master twice in a row today and cannot manage to progress to Class Reunion.

I did double-check that no AF items are in MH, with the storage moogle or in the inventory anywhere any more and all safely tossed. Relogged aswell. Issues are still the same.

Any advice? Thanks :)

**Comment by GM-Dave** [comment]
What is your ingame name?

Also please contact a GM in game and we'll see about getting this taken care of for you.

**Comment by Minnaa** [comment]
Ingame name: Minna :)

**Comment by GM-Dave** [comment]
Unfortunately the ability to re-complete AF quests is not implemented on the server yet, which would explain the fact that you couldn't progress past the AF1 quest (let alone be able to reflag it in the first place). Regardless since you had previously completed the AF questline I have reimbursed your AF gear.

Hopefully in the near future we will have implemented the ability for players to re-complete their AF quests. until then just be mindful with what you do with your AF gear.
