### ISSUE TITLE
Nokkhi Jinjahl - NPC (traveling circus) **Broken** Quiver Changer

### ISSUE THREAD

**Issue by Sirera** [myera/issues#264]
NPC changes bolt and arrow stacks into Quivers.
Tried to trade and character disconnected.

**Comment by GM-Dave** [comment]
This has been a known issue, party due to the reason of the broken/wonky conquest system.

As it stands there are (can be) 3 duplicate NPCs in each of the three starter nations (Southern San d'Oria neat the AH, Windurst Woods near the fountain, and Port Bastok also near the fountain.)

I would recommend try all THREE of the NPCs, as per Loco at least one of them should work (the Windurst Woods one namely). Please report back results, ty.

**Comment by mathantolous** [comment]
Some tips from trading for quivers: if you constantly DC try changing the number of stacks you are trading at a time.  It sounds strange but it does appear, for some users, the number of items traded will effect how frequently you DC.

**Comment by Minnaa** [comment]
I can confirm that sometimes the number of stacks traded will affect if the character crashes, if he/she receives the quivers as normally or if nothing happens.

However, even with a crash, the char will still receive the quivers. So at least there will be no items lost.

**Comment by GM-Dave** [comment]
I just tested this out myself. 2/3 of the NPCs (Bastok and Sandy) worked just fine. Windurst's seems to be just disabled entirely. **/ver 30161227_1**

Any further confirmation on whether this is still an issue or not for others would be appreciated.
