### ISSUE TITLE
No experience points gained if PL has hate when mob dies.

### ISSUE THREAD

**Issue by Manticmage** [myera/issues#27]
When a party is fighting a mob, if a power leveler has hate from curing the party, and is first on the mobs hate list when the mob dies, the party will receive no experience points. This is new as of March 9th.

**Comment by ericnuke** [comment]
It happens when your PL (or anyone not in your party) takes any type of damage from the mob. We tested this by fighting Cactuar, when PL was in 1000 needles range and took damage we got no exp. We fought it again and left PL out of range and we received exp. Both times the PL was not even on hate list because PL did not cast cure or anything.

**Comment by Mozzy4Ever** [comment]
This problem is still on-going. Really hurts for people who play during odd times when parties aren't usually running.

**Comment by Mozzy4Ever** [comment]
bump? lol

**Comment by GM-Dave** [comment]
This issue was fixed by a recent server update.
