### ISSUE TITLE
SMN behaving strangely

### ISSUE THREAD

**Issue by ManiekFenrir** [myera/issues#28]
So after the update, the following changes happened to SMN:
_note_ These are all the changes that I have been able to find so far there could be more that others have seen.
Previous Version behavior --> Current Version behavior
1.) Blood Pact ability was able to be used without assault from up  to 17.5 distance away  --> Blood Pact Abilities only land if the avatar is in melee range of the target, whether assault is used or you manually drag the avatar with you right next to the mob
2.) Single target Blood Pacts would claim the mob with or without assault (but not AOE BP  i.e. astral flow etc.) --> All Blood Pact abilities do not claim the monster, only assault does
3.) Apogee Job ability was not available  -->  Apogee Job Ability is now available but does not seem to work

**Comment by GM-Dave** [comment]
1) All BPs will work regardless if Avatar is engaged to mob or not, and are subject to their own distance regulations (i.e. if you use a melee pact but are not in melee range, the pact will go off regardless and be subject to cooldown. This is a known issue and non priority. The player should just be aware of their & pets location when using abilities)

2) So long as the causes damage and/or hits, should claim the mob as intended. Will not if it misses (this was not a SMN/Pet only occurance).

3) Apogee was introduced as part of DSP but has not been fully coded. Was not a original 75 cap job ability so it's implementation & usage on Era is not likely.

If there are still any issues since the most recent update please file a new ticket.
