### ISSUE TITLE
Monastic Cavern Mobs, Davoi Coffer Key

### ISSUE THREAD

**Issue by whateversclever1215** [myera/issues#314]
Era website says that orcish dreadnaughts in monastic cavern have up to 9% droprate on coffer keys.
I went and killed 15+ of those specifically but also 50+ mobs inside monastic cavern and never saw 1 coffer key. I saw much less loot than normal in general.
In addition, Monastic Cavern has about 3x the intended amount of enemies spawned.
Then I walked outside and tried the mobs that, according to era website lookup, have 2-3% droprate on coffer keys. I've gotten 2 of the 4 keys I need in <10 kills out here.
This was all with TH3. I think something is preventing coffer keys from dropping in monastic cavern.
I'm told if the era website says it's got a 9% droprate it's supposed to be true. Shouldn't be mathematically possible for me to have gone so far without seeing it without TH, right?

**Comment by GM-Dave** [comment]
I went and tested this personally, and upon my first kill got a key to drop off the Dreadnoughts. I personally saw the keys drop as intended off all the possible mobs. Mathematically, yes, it's unlikely but that's how RNG rolls sometimes. So far as I can tell you were just very unlucky with those mobs.

> In addition, Monastic Cavern has about 3x the intended amount of enemies spawned.
This is due to "mob wandering" being disabled. There aren't any more mobs then there should be in the zone, they unfortunately just all stay clustered together. This is a long standing issue with DSP (turning on mob roaming on this server cause tremendous lag, hence why it is disabled)

**Comment by GM-Dave** [comment]
For future reference issues of this nature (item/mob droprates) are generally Era specific issues with our server's database, and as such should be filed via the HelpDesk system ("Service Requests" under the Report tab on the main site)
