### ISSUE TITLE
Can't activate staging points. Missing KI.

### ISSUE THREAD

**Issue by Beastmaster1** [myera/issues#318]
I've started the mission Immortal Sentries but I don't have the KI Supplies Package required for it.

**Comment by GM-Dave** [comment]
You need to back track and make sure you've triggered all the pre-requisite cutscenes. Sometimes you may have to talk to the same NPC/watch same CS multiple times.

**Comment by Beastmaster1** [comment]
Actually I'm quite sure I actually did have the supplies package and gave it to the npc at Halvung as I'm able to warp there, but not back. It's been 2 years since I started the quest but I do remember having trouble with it back then.

As far as the guides say, the only NPCs involved are Naja Salaheem and the staging post NPCs. I must have spoken to Naja over 100 times after trying different things. I've also tried every single staging point NPC multiple times and none of them react. The runic portals don't respond either. 

I don't even want to think about how many hours I've wasted trying to figure this out. I can't think of anything left to try...

**Comment by GMYasiinEra** [comment]
has this been resolved? its a simple fix.

**Comment by Beastmaster1** [comment]
Hey. No, it hasn't. How do I fix it?

**Comment by GMYasiinEra** [comment]
i do :P  simple GM command lemme know next time youre online.. also this is a service request.. for the future use the helpdesk to file a tick like this next time not the git.. the git i dont check as often because it is supposed to be related to code only and not actual legit service requests like this one.. www.ffera.com/tickets if youre unsure..
