### ISSUE TITLE
Bastok Mission 1-3: Text glitches

### ISSUE THREAD

**Issue by Mykezero** [myera/issues#348]
For Bastok mission 1-3: [Fetichism](http://ffxiclopedia.wikia.com/wiki/Fetichism), when interacting with Rashid for the second time in Bastok Mines, he attempts to repeat what items are needed to complete the quest, but he replies with empty / blank spaces in place of the item names. 

Also, when you first accept the mission, and click the Yes option, the no option is appended to the chat even though it was not selected. 

![image](https://user-images.githubusercontent.com/5349608/31312693-27ec3674-ab98-11e7-8b4c-70b6fcdfff3f.png)

**Comment by dwn134** [comment]
Can you submit a ticket at ffera.com under helpdesk. We don't normally monitor this area

**Comment by Mykezero** [comment]
Yeah, I can do that.

**Comment by Mykezero** [comment]
@dwn134 New ticket has been created under Quests/Missions in helpdesk. 

Thanks for your help! ^^

**Comment by GM-Dave** [comment]
Chances are this is due to an incompatibility between the current server version and your installed client versions (most Text ID issues are).

As of the time of this posting there will be a server update taking place, so make sure you've updated your game client by following this guide https://www.youtube.com/watch?v=OrnAPMJkGww&t
