### ISSUE TITLE
Phantom Rolls anmations

### ISSUE THREAD

**Issue by Aerixaa** [myera/issues#59]
Hello everyone,

Dancer's Roll Scholar Roll's Animation not working at all.

Thanks for the hard work and keep up the good work.

**Comment by Minnaa** [comment]
I can confirm this. And I'd like to add that instead of the "Phantom Roll" animation with the roll numbers showing, for those two rolls it is replaced by the "Snake eye" animation. This can be confusing, because it will always show the 1 and the actual rolled number has to be looked up in the chatlog. But so far it only seems to be an animation issue. :)
